name: Build signed Nudge for pull requests (prerelease)

on:
  pull_request_target:
    branches:
    - development

jobs:
  build:
    runs-on: macos-11

    steps:
    - name: Checkout nudge repo
      uses: actions/checkout@v2

    - name: Install Apple Xcode certificates
      uses: apple-actions/import-codesign-certs@253ddeeac23f2bdad1646faac5c8c2832e800071
      with:
        keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
        p12-file-base64: ${{ secrets.APP_CERTIFICATES_P12 }}
        p12-password: ${{ secrets.APP_CERTIFICATES_P12_PASSWORD }}

    - name: Install Apple Installer certificates
      uses: apple-actions/import-codesign-certs@253ddeeac23f2bdad1646faac5c8c2832e800071
      with:
        create-keychain: false # do not create a new keychain for this value
        keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
        p12-file-base64: ${{ secrets.PKG_CERTIFICATES_P12 }}
        p12-password: ${{ secrets.PKG_CERTIFICATES_P12_PASSWORD }}

    - name: Run build package script
      run: ./build_nudge.zsh
